# Generated by Django 5.1.8 on 2025-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('product', models.CharField(choices=[('web-sayt-yaratish', 'Web sayt yaratish'), ('mobil-ilova-yaratish', 'Mobil ilova yaratish'), ('seo-xizmatlari', 'SEO xizmatlari'), ('digital-marketing', 'Digital marketing'), ('brending', 'Brending'), ('grafik-dizayn', 'Grafik dizayn'), ('video-tahrirlash', 'Video tahrirlash'), ('kontent-yaratish', 'Kontent yaratish'), ('smm', 'SMM'), ('onlayn-kurslar', 'Onlayn kurslar'), ('telegram-bot', 'Telegram bot'), ('boshqa', 'Boshqa')], max_length=200)),
                ('product_description', models.TextField()),
                ('budget', models.CharField(choices=[("5-million-so'mgacha", "5 million so'm"), ("5-10-million-so'm", "5-10 million so'm"), ("10-20-million-so'm", "10-20 million so'm"), ("20-50-million-so'm", "20-50 million so'm"), ("50-million-so'mdan-yuqori", "50 million so'mdan yuqori"), ('boshqa', 'Boshqa')], max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
